version: '3.8'

services:
  frontend:
    build:
      context: ./svelte-frontend
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
      - VITE_API_URL=http://backend:8080
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: rust-backend/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - RUST_ENV=production
      - ORACLE_CONNECTION_STRING=oracle://system:${ORACLE_PASSWORD}@host.docker.internal:1521/XEPDB1
      - DATABASE_URL=oracle://system:$system@localhost:1521/free

volumes:
  oracle_data:

