version: '3.8'

services:
  oracle-db:
    image: container-registry.oracle.com/database/free:latest
    container_name: oracle-db
    ports:
      - "1521:1521"
    environment:
      - ORACLE_PWD=oracle123  # Default password that will be changed
    volumes:
      - oracle_data:/opt/oracle/oradata
      - ./scripts:/opt/oracle/scripts
    healthcheck:
      test: ["CMD", "sqlplus", "-L", "sys/oracle123@//localhost:1521/FREEPDB1 as sysdba", "@/opt/oracle/scripts/healthcheck.sql"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  oracle_data: 