version: '3.8'

services:
  frontend:
    build:
      context: ./svelte-frontend
      target: builder
    ports:
      - "5173:5173"
    volumes:
      - ./svelte-frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:8080
    command: bun run dev --host

  backend:
    build:
      context: ./rust-backend
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    volumes:
      - ./rust-backend:/app
    environment:
      - RUST_ENV=development
      - ORACLE_CONNECTION_STRING=oracle://system:oracle@oracle:1521/XEPDB1
    depends_on:
      - oracle

  oracle:
    image: container-registry.oracle.com/database/express:21.3.0-xe
    ports:
      - "1521:1521"
      - "5500:5500"
    environment:
      - ORACLE_PWD=oracle
      - ORACLE_CHARACTERSET=AL32UTF8
    volumes:
      - oracle_data:/opt/oracle/oradata

volumes:
  oracle_data: 