name: Svelte Frontend CI/CD

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        working-directory: ./svelte-frontend
        run: bun install

      - name: Run type checking
        working-directory: ./svelte-frontend
        run: bun run check

      - name: Run linting
        working-directory: ./svelte-frontend
        run: bun run lint

      - name: Build project
        working-directory: ./svelte-frontend
        run: bun run build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: svelte-frontend-build
          path: svelte-frontend/build/
